# Generated by Django 5.0.6 on 2026-01-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_shopitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='avg_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.rank'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='playerperformance',
            constraint=models.UniqueConstraint(fields=('account_id', 'match_id'), name='uniq_perf_account_match'),
        ),
    ]
