# Generated by Django 5.0.6 on 2026-01-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_match_avg_rank_alter_match_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='upgrades_into',
        ),
        migrations.CreateModel(
            name='ShopItemUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_edges_from', to='tracker.shopitem')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_edges_to', to='tracker.shopitem')),
            ],
        ),
        migrations.AddField(
            model_name='shopitem',
            name='upgrades_into',
            field=models.ManyToManyField(blank=True, related_name='upgraded_from', through='tracker.ShopItemUpgrade', to='tracker.shopitem'),
        ),
        migrations.AddConstraint(
            model_name='shopitemupgrade',
            constraint=models.UniqueConstraint(fields=('from_item', 'to_item'), name='uniq_shopitem_upgrade_edge'),
        ),
    ]
