# Generated by Django 5.0.6 on 2026-01-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_shopitem_upgrades_into_shopitemupgrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeritem',
            name='imbued_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.ability'),
        ),
        migrations.AddIndex(
            model_name='playerability',
            index=models.Index(fields=['match_id'], name='idx_pability_match'),
        ),
        migrations.AddIndex(
            model_name='playerability',
            index=models.Index(fields=['match_id', 'account_id'], name='idx_pability_match_account'),
        ),
        migrations.AddIndex(
            model_name='playerability',
            index=models.Index(fields=['match_id', 'account_id', 'game_time'], name='idx_pability_match_acc_t'),
        ),
        migrations.AddIndex(
            model_name='playeritem',
            index=models.Index(fields=['match_id'], name='idx_pitem_match'),
        ),
        migrations.AddIndex(
            model_name='playeritem',
            index=models.Index(fields=['match_id', 'account_id'], name='idx_pitem_match_account'),
        ),
        migrations.AddIndex(
            model_name='playeritem',
            index=models.Index(fields=['match_id', 'account_id', 'game_time'], name='idx_pitem_match_acc_t'),
        ),
        migrations.AddConstraint(
            model_name='playerability',
            constraint=models.UniqueConstraint(fields=('account_id', 'match_id', 'ability_id', 'game_time'), name='uniq_playerability_event'),
        ),
        migrations.AddConstraint(
            model_name='playeritem',
            constraint=models.UniqueConstraint(fields=('account_id', 'match_id', 'item_id', 'game_time'), name='uniq_playeritem_purchase'),
        ),
    ]
