# Generated by Django 5.0.6 on 2026-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_playeritem_imbued_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_notable',
            field=models.BooleanField(default=False),
        ),
    ]
